[package]
name = "on-chain-academic-leaderboards"
version = "1.0.0"
authors = []

[addresses]
MyModule = "0x2ccd15ceddfbf8abdb3ff8d941463e9c7eaa6715ea90e8de837fe852d6b22426"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dev-dependencies]
